### ISSUE TITLE
CommonJS Nav requires ES6 Utilities

### ISSUE THREAD

**Issue by nappy** [OfficeDev/office-ui-fabric-react#10387]
If I try to use "Nav" from "lib-commonjs" using 7.31.1 in an commonjs (node) environment this happens:

```
C:\...\node_modules\office-ui-fabric-react\lib\Utilities.js:1
import './version';
       ^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\...\node_modules\office-ui-fabric-react\lib-commonjs\components\Nav\Nav.base.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Reason being this absolute import of the non-commonjs version in Nav.base.js:

`var Utilities_2 = require("office-ui-fabric-react/lib/Utilities");`

The latest non affected version is 7.28.3

**Comment by nappy** [comment]
@inateeg @Vitalius1 Please look into this.

**Comment by natalieethell** [comment]
@nappy Thanks for reporting this issue! We'll look into a fix.

**Comment by natalieethell** [comment]
Ah, looks like someone already submitted a fix. The issue should be fixed with this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/10335/files. Let me know if that works for you!

**Comment by natalieethell** [comment]
Ah, just one second. I'll kick off a new release build.

**Comment by natalieethell** [comment]
Alright, v7.31.2 should have the changes you're looking for! Let us know if that fixes your issue.

**Comment by nappy** [comment]
Yes 7.31.2 fixes the issue, thanks.

**Comment by natalieethell** [comment]
Great! I'll close out this issue.
