### ISSUE TITLE
Migration: Update Snapshots Fails in Windows

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#11464]
### Environment Information

- **Package version(s)**: 7.73.0
- **Browser and OS versions**: Windows 10

### Please provide a reproduction of the bug in a codepen:

`yarn buildto migrations` - ensure migrations package was built
`yarn update-snapshots` - this can be run either from repo root or `packages/migration` to repro the issue

Update snapshots command fails on multiple tests:
```
  ● warnAutobindRemoved › warns when autobind is used

    ENOENT, no such file or directory '\\?\C:\Users\Jason\src\oufr-jg-i\packages\migration\_root\7.0.0\autobind.tsx'

      53 |   try {
      54 |     migration.step({ dryRun: false, warn: (msg: string) => result.warnings.push(msg) });
    > 55 |     const contents = await readFileAsync(path.join('_root', filename));
         |                            ^
      56 |     teardown();
      57 |     result.contents = contents.toString();
      58 |     return result;

      at Object.<anonymous> (../../node_modules/mock-fs/lib/binding.js:520:15)
      at maybeCallback (../../node_modules/mock-fs/lib/binding.js:68:18)
      at Object.<anonymous>.Binding.open (../../node_modules/mock-fs/lib/binding.js:493:10)
      at Object.<anonymous> (../../node_modules/mock-fs/lib/index.js:33:39)
      at Object.<anonymous> (src/tests/mods/utils/index.ts:55:28)
      at fulfilled (../../node_modules/tslib/tslib.js:107:62)
```
![image](https://user-images.githubusercontent.com/26070760/70831507-9a147f80-1da7-11ea-9442-4e64b9ce23b5.png)

#### Actual behavior:

`yarn update-snapshots` fails on jest tests.

#### Expected behavior:

`yarn update-snapshots` should not fail on jest tests without local changes.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
While working on updating build commands in the repo, I discovered this isn't just specific to updating snapshots. Running `yarn jest` in `packages/migrations` also fails. It seems migration unit tests aren't running as part of the default `yarn build`, but probably should be.
