### ISSUE TITLE
TypeError in Panel: clientHeight of undefined

### ISSUE THREAD

**Issue by Ryu36** [OfficeDev/office-ui-fabric-react#1362]
### Bug Report

- __Package version(s)__: 2.7.1
- __Browser and OS versions__: Chrome 56.0.2924.87 / Windows Server 2012 R2

#### Describe the issue:

React Exception when using the Panel:

Exception in Panel.componentDidUpdate(): TypeError: Cannot read property 'clientHeight' of undefined
    at Panel._updateFooterPosition (http://localhost:8080/vendor.js:34492:30)
    at Panel.componentDidUpdate (http://localhost:8080/vendor.js:34408:18)
    at Panel.obj.(anonymous function) [as componentDidUpdate] (http://localhost:8080/vendor.js:26834:42)
    at measureLifeCyclePerf (http://localhost:8080/vendor.js:37907:12)
    at http://localhost:8080/vendor.js:38561:11
    at CallbackQueue.notifyAll (http://localhost:8080/vendor.js:23489:22)
    at ReactReconcileTransaction.close (http://localhost:8080/vendor.js:43002:26)
    at ReactReconcileTransaction.closeAll (http://localhost:8080/vendor.js:17485:25)
    at ReactReconcileTransaction.perform (http://localhost:8080/vendor.js:17432:16)
    at ReactUpdatesFlushTransaction.perform (http://localhost:8080/vendor.js:17419:20)

Panel is defined like:

`<Panel
                    headerText="New Something"
                    isLightDismiss={true}
                    isOpen={this.state.showNewForm}
                    onDismiss={this.closePanel.bind(this)}>`...
`</Panel>`

**Comment by NickSevens** [comment]
I experience kind of the same issue. However - for me it only occurs when defining multiple Panels on the page.
However the error occurs on different moments:
- When **nesting** 2 panels, the error occurs only when **closing** then parent panel
- When putting 2 panels side-by-side, the error occurs both when **opening** and **closing** the panel.

**Comment by Ryu36** [comment]
Good advice. 
Another component of my site renders a second panel, too.
So I have multiple panels in one site. Assigning keys made no difference.

**Comment by micahgodbolt** [comment]
I was able to get it to repro in a codepen, so I'll check it out soon.

**Comment by dzearing** [comment]
Fix was merged.
