### ISSUE TITLE
Cannot use Callout with targetElement

### ISSUE THREAD

**Issue by hckhanh** [OfficeDev/office-ui-fabric-react#1669]
### Bug Report

- __Package version(s)__: 2.23.2
- __Browser and OS versions__: 58.0.3029.81 (64-bit)/Windows 10 Pro

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

#### Describe the issue:

I cannot use Callout component

#### Actual behavior:

It did not appear and show error

```

BaseComponent.js:221 Exception in Layer.componentDidUpdate(): Exception in CalloutContent.componentDidMount(): TypeError: element.getBoundingClientRect is not a function
    at _getRectangleFromHTMLElement (http://localhost:3000/index.js:26449:34)
    at Object._getTargetRectDEPRECATED (http://localhost:3000/index.js:26435:35)
    at Object.getRelativePositions (http://localhost:3000/index.js:26335:124)
    at CalloutContent._updatePosition (http://localhost:3000/index.js:23606:46)
    at CalloutContent._onComponentDidMount (http://localhost:3000/index.js:23589:14)
    at CalloutContent.componentDidMount (http://localhost:3000/index.js:23512:14)
    at CalloutContent.obj.(anonymous function) [as componentDidMount] (http://localhost:3000/index.js:9117:42)
    at http://localhost:3000/index.js:28991:25
    at measureLifeCyclePerf (http://localhost:3000/index.js:28801:12)
    at http://localhost:3000/index.js:28990:11
BaseComponent.onError @ BaseComponent.js:221
obj.(anonymous function) @ BaseComponent.js:213
Layer.componentDidMount @ Layer.js:47
obj.(anonymous function) @ BaseComponent.js:207
(anonymous) @ ReactCompositeComponent.js:265
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:264
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
BaseComponent.js:221 Exception in Layer.componentDidMount(): Exception in Layer.componentDidUpdate(): Exception in CalloutContent.componentDidMount(): TypeError: element.getBoundingClientRect is not a function
    at _getRectangleFromHTMLElement (http://localhost:3000/index.js:26449:34)
    at Object._getTargetRectDEPRECATED (http://localhost:3000/index.js:26435:35)
    at Object.getRelativePositions (http://localhost:3000/index.js:26335:124)
    at CalloutContent._updatePosition (http://localhost:3000/index.js:23606:46)
    at CalloutContent._onComponentDidMount (http://localhost:3000/index.js:23589:14)
    at CalloutContent.componentDidMount (http://localhost:3000/index.js:23512:14)
    at CalloutContent.obj.(anonymous function) [as componentDidMount] (http://localhost:3000/index.js:9117:42)
    at http://localhost:3000/index.js:28991:25
    at measureLifeCyclePerf (http://localhost:3000/index.js:28801:12)
    at http://localhost:3000/index.js:28990:11
BaseComponent.onError @ BaseComponent.js:221
obj.(anonymous function) @ BaseComponent.js:213
(anonymous) @ ReactCompositeComponent.js:265
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:264
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
BaseComponent.js:222 Uncaught Exception in Layer.componentDidMount(): Exception in Layer.componentDidUpdate(): Exception in CalloutContent.componentDidMount(): TypeError: element.getBoundingClientRect is not a function
    at _getRectangleFromHTMLElement (http://localhost:3000/index.js:26449:34)
    at Object._getTargetRectDEPRECATED (http://localhost:3000/index.js:26435:35)
    at Object.getRelativePositions (http://localhost:3000/index.js:26335:124)
    at CalloutContent._updatePosition (http://localhost:3000/index.js:23606:46)
    at CalloutContent._onComponentDidMount (http://localhost:3000/index.js:23589:14)
    at CalloutContent.componentDidMount (http://localhost:3000/index.js:23512:14)
    at CalloutContent.obj.(anonymous function) [as componentDidMount] (http://localhost:3000/index.js:9117:42)
    at http://localhost:3000/index.js:28991:25
    at measureLifeCyclePerf (http://localhost:3000/index.js:28801:12)
    at http://localhost:3000/index.js:28990:11
BaseComponent.onError @ BaseComponent.js:222
obj.(anonymous function) @ BaseComponent.js:213
(anonymous) @ ReactCompositeComponent.js:265
measureLifeCyclePerf @ ReactCompositeComponent.js:75
(anonymous) @ ReactCompositeComponent.js:264
notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
```

**Comment by hckhanh** [comment]
I find out the relevant examples are not update accordingly. The `targetElement` prop is deprecated. I have to use `target` instead.
