### ISSUE TITLE
TypeError: Cannot read property 'palette' of undefined

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#1952]
After upgrading to the lastest version I get this error for all my Buttons

localhost:4321/dist/tr-form.bundle.js:30665 Exception in PrimaryButton.render(): TypeError: Cannot read property 'palette' of undefined
    at https://localhost:4321/dist/tr-form.bundle.js:46306:25
    at Object.memoizedFunction [as getStyles] (https://localhost:4321/dist/tr-form.bundle.js:33095:37)
    at PrimaryButton.render (https://localhost:4321/dist/tr-form.bundle.js:46285:214)
    at PrimaryButton.obj.(anonymous function) [as render] (https://localhost:4321/dist/tr-form.bundle.js:30651:43)
    at d._renderValidatedComponentWithoutOwnerOrContext (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:518398)
    at d._renderValidatedComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:518525)
    at d.performInitialMount (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:514366)
    at d.mountComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:513412)
    at Object.mountComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:89:92008)
    at d.performInitialMount (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:514526)
    at d.mountComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:513412)

How do I fix this?

**Comment by russgove** [comment]
ok, I see the theming stuff was added so I  added the line
import {getTheme} from  "@uifabric/styling";``

and then on my buttons id set the theme 
<PrimaryButton theme={getTheme()} 

That fixed the buttons, but the dropdowns are also not working.
I am getting errors like:
localhost:4321/dist/tr-form.bundle.js:30329 Exception in Layer.componentDidMount(): Exception in Layer.componentDidUpdate(): Exception in CommandButton.render(): TypeError: Cannot read property 'palette' of undefined
    at https://localhost:4321/dist/tr-form.bundle.js:45950:53
    at Object.memoizedFunction [as getStyles] (https://localhost:4321/dist/tr-form.bundle.js:32759:37)
    at https://localhost:4321/dist/tr-form.bundle.js:46055:49
    at Object.memoizedFunction [as getStyles] (https://localhost:4321/dist/tr-form.bundle.js:32759:37)
    at CommandButton.render (https://localhost:4321/dist/tr-form.bundle.js:46032:169)
    at CommandButton.obj.(anonymous function) [as render] (https://localhost:4321/dist/tr-form.bundle.js:30315:43)
    at d._renderValidatedComponentWithoutOwnerOrContext (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:518398)
    at d._renderValidatedComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:518525)
    at d.performInitialMount (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:514366)
    at d.mountComponent (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-05-26.017/workbench-assembly_en-us_9bebc1c8981e7b330bf485cb81b74e89.js:110:513412)

I see that  the dropdown uses a commandbuttton internally. How do I set it's theme? 
How do I set a 'global' theme so I don't need to do thison each control. 

This is in an spfx react webpart.

**Comment by jhdrn** [comment]
I updated to 4.4.2 and the button problem was gone.

**Comment by mikewheaton** [comment]
@russgove: Does updating to 4.4.2 also fix this issue for you? Please reopen if not.

**Comment by russgove** [comment]
I think upgrading to 4.4.2 cause my issue

**Comment by lordpeppe** [comment]
I am also having a similar issue. Have any of found a solution?

**Comment by russgove** [comment]
ok, I see the theming stuff was added so I added the line
import {getTheme} from "";``

and then on my buttons id set the theme
<PrimaryButton theme={getTheme()}

That fixed the buttons, but the dropdowns are also not working.

**Comment by russgove** [comment]
How DO I reopen this issue?

**Comment by russgove** [comment]
you cannot re-open your own issues if a repo collaborator closed them

**Comment by ismailme** [comment]
Same issue...

**Comment by russgove** [comment]
OK, So I have an existing spfx app with 
`	    "office-ui-fabric-react": "^2.25.1",`

I ran 
      ```
 npm uninstall office-ui-fabric-react	--save
	npm i office-ui-fabric-react@latest --save
```

and got version 4.7.0

The app builds but at runtime I get the error Uncaught (in promise) Exception in PrimaryButton.render(): TypeError: Cannot read property 'palette' of....

Added code 
import {getTheme } from '@uifabric/styling/lib/utilities/theme';

and changed all the buttons to have theme={getTheme()}

Now no errors on page load, but when I hit any Dropdowns I get 
tr-form.bundle.js:31009 Uncaught Exception in Layer.componentDidMount(): Exception in Layer.componentDidUpdate(): Exception in CommandButton.render(): TypeError: Cannot read property 'palette' of undefined at https://localhost:4321/dist/tr-form.bundle.js:44640:53 at Object.memoizedFunction [as getStyles] (https://localhost:4321/dist/tr-form.bundle.js:33454:37) at https://localhost:4321/dist/tr-form.bundle.js:44745:49 at Object.memoizedFunction [as getStyles] (https://localhost:4321/dist/tr-form.bundle.js:33454:37) at CommandButton.render (https://localhost:4321/dist/tr-form.bundle.js:44722:169) at CommandButton.obj.(anonymous function) [as render] (https://localhost:4321/dist/tr-form.bundle.js:30994:43) at d._renderValidatedComponentWithoutOwnerOrContext (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-06-02.

I tried adding theme=gettheme() to the DropDowns but that give me a compiler error.

Suspect the dopdown control has an embedded button or something.

IIs there a way we are supposed to set the global theme?

**Comment by pmizuno** [comment]
Getting this problem when using the people picker component.
