### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'get' of undefined SPhttpClient.get

### ISSUE THREAD

**Issue by halfice** [OfficeDev/office-ui-fabric-react#3591]
I created a class MyHttp inside component folder. I have import all required classes from @microsoft/sp-http but when run the project this.context.sphttpclient.get is null.
Same code I run outside the component class i.e in my main webpart.ts file than it works.

Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at MyHttp._getListData (MyHttp.tsx:168)
    at MyHttp._renderListAsync (MyHttp.tsx:181)
    at MyHttp.componentDidMount (MyHttp.tsx:160)
    at react-dom.js:4719
    at measureLifeCyclePerf (react-dom.js:4529)
    at react-dom.js:4718
    at CallbackQueue.notifyAll (react-dom.js:948)
    at ReactReconcileTransaction.close (react-dom.js:11398)
    at ReactReconcileTransaction.closeAll (react-dom.js:14790)
    at ReactReconcileTransaction.perform (react-dom.js:14737)

**Comment by lambertwang** [comment]
Can you share a code example or a codepen that reproduced your issue?

**Comment by bilalkhan870** [comment]
i am facing some issues with Alert notification,
TypeError: Cannot read property 'spHttpClient' of undefined
at alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15
at new Promise ()
at e._loadUpcomingAlerts (alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15)
at alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15
(anonymous) @ alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15
Promise.catch (async)

Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-12.003/sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83:420
at a (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-12.003/sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83:523)
at render (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-07-12.003/sp-pages-assembly_en-us_5c471fe29dde54003a64b536019ac3d3.js:83:104206)
at https://alsaqergroup.sharepoint.com/sites/APPS/ClientSideAssets/3624777a-337d-4b34-8384-5ab774c069aa/alert-notitication-application-customizer_305d9f3b4db760783a37c56ab84b6326.js:15:258561

thanks in advance
