### ISSUE TITLE
NormalPeoplePicker with item limit on IE11 issue

### ISSUE THREAD

**Issue by aluczak** [OfficeDev/office-ui-fabric-react#3873]
### Bug Report

- __Package version(s)__: 5.45.3
- __Browser and OS versions__: IE11 (11.125.16299.0)

#### Priorities and help requested

Requested priority: Normal 

#### Describe the issue:

1. Use following code with any itemLimit:
<NormalPeoplePicker
     onChange={(val) => {}}
     onResolveSuggestions={this._onFilterChanged}
     itemLimit={5} />    
(_onFilterChanged implementation is from PeoplePicker example on 
https://developer.microsoft.com/en-us/fabric#/components/peoplepicker)

2. Write something in the people picker
3. See suggestions
4. First one is automatically highlighted
5. Hit enter or tab on keyboard (do not use mouse)

#### Actual behavior:
Component rendering crashes with following error:
Exception in NormalPeoplePicker.render(): TypeError: Unable to get property 'inputElement' of undefined or null reference
   at BasePicker.prototype.renderSuggestions (.../Scripts/submit-content-for-approval.js:42290:10)
   at BasePicker.prototype.render (.../Scripts/submit-content-for-approval.js:42272:10)
   at obj[methodName] (.../Scripts/submit-content-for-approval.js:16994:22)
   at h (.../lib/react/react-dom.production.min.js:130:356)
   at beginWork (.../lib/react/react-dom.production.min.js:133:473)
   at d (.../lib/react/react-dom.production.min.js:158:387)
   at f (.../lib/react/react-dom.production.min.js:159:212)
   at g (.../lib/react/react-dom.production.min.js:159:462)
   at t (.../lib/react/react-dom.production.min.js:167:1)
   at x (.../lib/react/react-dom.production.min.js:166:247)

#### Expected behavior:

The item is selected the same way as by clicking it.

Note that this works fine on all other common browsers, like Chrome, Firefox, even Edge.

**Comment by bratukham** [comment]
I am getting the same problem when use `CompactPeoplePicker` (office-ui-fabric-react v.5.56.1).

I've investigated the problem and figured out that the problem is in the BasePicker.tsx.
The `renderSuggestions` function will be called twice after selecting a person via `enter`.
The first time `this.input` property is valid, i.e. not `null` and `suggestionsVisible` state is `true`.
The second time `this.input` property is `undefined` and `suggestionsVisible` state is **still** `true`. Right here comes the exception.

The possible fix would be to change this check:
``` jsx
  protected renderSuggestions(): JSX.Element | null {
    const TypedSuggestion = this.SuggestionOfProperType;
    return this.state.suggestionsVisible ? (
      <Callout
...
```
to this one:
``` jsx
  protected renderSuggestions(): JSX.Element | null {
    const TypedSuggestion = this.SuggestionOfProperType;
    return this.state.suggestionsVisible && this.input ? ( // <- HERE
      <Callout
...
```

But I'm not sure whether it is a good way to fix the problem. Maybe somebody has a better solution for this bug?

Also it is possible to reproduce the exception in Chrome v64.0.3282.186 when setting just one breakpoint 
in the handler of the `enter`, i.e. here:
``` jsx
case KeyCodes.up:
        if (ev.target === this.input.inputElement && this.state.suggestionsVisible) { // <- here breakpoint
          if (this.suggestionElement.tryHandleKeyDown(keyCode, this.suggestionStore.currentIndex)) {
...
```
and then just let it run by pressing F8. The exception will appear immediately.
