### ISSUE TITLE
loadStyles always called when importing ActivityItem (or anything importing scroll.js/scroll.scss.js) - which breaks Node & SSR

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#4287]
### Bug Report

- __Package version(s)__: office-fabric-react@5.52.0
- __Browser and OS versions__: Node 9.X

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Office Sway

#### Describe the issue:

We need to be able to test Office Fabric in a pure Node environment as part of our Jest end-to-end tests. Creating a UI Fabric React element, for example, `"{ ActivityItem } from "office-ui-fabric-react";` immediately calls to `document`.

```typescript
import { ActivityItem, IActivityItemProps } from "office-ui-fabric-react";

describe("SSR", () => {
	it("doesn't crash", () => {
		const props: IActivityItemProps = {};
		const element = <ActivityItem {...props} />;
	});
});
```

#### Actual behavior:

This crashes in Node because `document` doesn't exist.
Call stack below; in summary:

* `ActivityItem` imports `Utilities`
* `Utilities` imports `AutoScroll`
* `AutoScroll` imports `scroll`
* `scroll` imports `scroll.scss.js`
* `scroll.scss.js` immediately calls `load_themed_styles_1.loadStyles([{ "rawString": ".scrollDisabled_94ac5891{overflow:hidden !important}\n" }]);`

```text
 FAIL  test\end-to-end\ssr.test.tsx
  ● Test suite failed to run

    ReferenceError: document is not defined

      at registerStyles (node_modules/@microsoft/load-themed-styles/lib/index.js:278:16)
      at applyThemableStyles (node_modules/@microsoft/load-themed-styles/lib/index.js:140:13)
      at node_modules/@microsoft/load-themed-styles/lib/index.js:82:13
      at measure (node_modules/@microsoft/load-themed-styles/lib/index.js:32:5)
      at Object.loadStyles (node_modules/@microsoft/load-themed-styles/lib/index.js:69:5)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/node_modules/@uifabric/utilities/lib/scroll.scss.js:5:22)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/node_modules/@uifabric/utilities/lib/scroll.js:4:14)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/node_modules/@uifabric/utilities/lib/AutoScroll.js:4:16)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/node_modules/@uifabric/utilities/lib/index.js:5:22)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/Utilities.js:4:22)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/components/ActivityItem/ActivityItem.js:7:19)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/components/ActivityItem/index.js:4:22)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/ActivityItem.js:4:22)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/index.js:8:22)
      at Object.<anonymous> (test/end-to-end/ssr.test.tsx:6:34)
```

#### Expected behavior:

This shouldn't happen until the element is mounted.

For now, we're using Webpack's `null-loader` to stub out anything from `office-ui-fabric-react` on an unreleased set of views. We need to be able to render the HTML for these things in at least tests.

**Comment by dzearing** [comment]
in our ssr test, we had to initialize a few things.

```tsx
import { initializeIcons } from 'office-ui-fabric-react/lib/Icons';
initializeIcons('dist/');

// Configure load-themed-styles to avoid registering styles.
let themeLoader = require('@microsoft/load-themed-styles');
themeLoader.configureLoadStyles((styles) => {
  // noop
});

// Set ssr mode to true, and rtl to false.
let library = require('office-ui-fabric-react/lib/Utilities');
library.setSSR(true);
library.setRTL(false);

// Assume a large screen.
let responsiveLib = require('office-ui-fabric-react/lib/utilities/decorators/withResponsiveMode');
responsiveLib.setResponsiveMode(responsiveLib.ResponsiveMode.large);
```

Does this help? Basically you will want to not be rendering styles in this case.

**Comment by dzearing** [comment]
Oh! Also, in jest, we have this in our config:

```ts
        moduleNameMapper: {
          '\\.(scss)$': path.resolve(__dirname, 'jest-style-mock.js'),
        }
```

which just empties it out:

```ts
module.exports = {};
```

Which removes all sass files.

**Comment by JoshuaKGoldberg** [comment]
Thanks for the tips @dzearing! I'll try them out and post here if there are any problems.

Are these methods documented anywhere? If not, where should I add docs for them?

**Comment by michaelangotti** [comment]
@JoshuaKGoldberg Has this been resolved? Can we close? Thanks!

**Comment by oengusmacinog** [comment]
@JoshuaKGoldberg for documentation we have a [Testing Page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Testing) in the wiki but it doesn't look like this is included yet.

**Comment by JoshuaKGoldberg** [comment]
I'll send a PR to the testing page that'll mark this issue as fixed!
