### ISSUE TITLE
Jest unittests: Cannot redefine property: DetailsListBase

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#5971]
### Bug Report 
 
- __Package version(s)__: ABOVE 6.47.2
- React 16.x, 
- Jest 23.5.0
- enzype 3.4.2
- typescript 2.9.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 

#### Describe the issue:

Doing snapshot unittests are currently failing. In Version 6.47.2 they are working. In all newer releases the unittests failing in jest.
It seems that fabric is sometims importing thing multiple times - which might phase jest sometimes.
A simple unittest with <DetailsList> component leads to no issues. 

Unfortunately I could not isolate the problem a bit more  up to now as we are snapshottesting more complex components with many nested components.
 
#### Actual behavior:
 Some of our snapsot unittests failing.

`Test suite failed to run

    TypeError: Cannot redefine property: DetailsListBase
        at Function.defineProperty (<anonymous>)
at node_modules/office-ui-fabric-react/lib/components/DetailsList/index.js:4:113
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/components/DetailsList/index.js:4:28)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/DetailsList.js:1:753)
      at Object.<anonymous> (src/components/Roles/ProviderDetails.tsx:5:20)
      at Object.<anonymous> (src/components/ResourceGroups/ResourceGroupOperations.tsx:21:24)
      at Object.<anonymous> (src/tests/resourcegroups.test.tsx:11:216)` 

#### Expected behavior:
 
jest unittest running as before.

**Comment by kenotron** [comment]
looks like the culprit is 
```export * from './DetailsList.base';```

inside DetailsList.tsx. I'll have a PR out shortly... without a repro though I don't know if I would have fixed it for you.
