### ISSUE TITLE
fabric-website can not start

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7454]
### Environment Information 
 
 
- __Package version(s)__: git master
- __Browser and OS versions__:  Windows 10

### Please provide a reproduction of the bug in a codepen:
 
```
git clone https://github.com/OfficeDev/office-ui-fabric-react.git
npm install
cd apps/fabric-website/
npm start
```
 
#### Actual behavior:
 
```
ERROR in ./src/components/Nav/Nav.tsx
Module not found: Error: Can't resolve '@uifabric/experiments' in 'C:\Users\liuyang\ReactProjects\office-ui-fabric-react\apps\fabric-website\src\components\Nav'
 @ ./src/components/Nav/Nav.tsx 8:20-52
 @ ./src/components/App/App.tsx
 @ ./src/root.tsx
 @ multi C:/Users/liuyang/ReactProjects/office-ui-fabric-react/common/temp/node_modules/.registry.npmjs.org/webpack-dev-server/3.1.4/webpack@4.7.0/node_modules/webpack-dev-server/client?http://localhost:4321 ./src/root.tsx
i ｢wdm｣: Failed to compile.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/CodeBlock/CodeBlock.tsx(3,31):
TS2307: Cannot find module './CodeBlock.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/ColorTable/ColorTable.tsx(3,31):
TS2307: Cannot find module './ColorTable.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/IconGrid/IconGrid.tsx(3,31):
TS2307: Cannot find module './IconGrid.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/Nav/Nav.tsx(11,8):
TS2307: Cannot find module '@uifabric/experiments'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/Nav/Nav.tsx(14,31):
TS2307: Cannot find module './Nav.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/PageHeader/PageHeader.tsx(3,31):
TS2307: Cannot find module './PageHeader.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/Table/Table.tsx(3,31):
TS2307: Cannot find module './Table.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/components/TopNav/TopNav.tsx(8,31):
TS2307: Cannot find module './TopNav.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/BlogPage/BlogPage.tsx(4,31):
TS2307: Cannot find module './BlogPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/GetStarted/GetStartedPage.tsx(8,31):
TS2307: Cannot find module './GetStartedPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/HomePage/HomePage.tsx(3,31):
TS2307: Cannot find module './HomePage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Interstitials/AngularJSPage.tsx(3,31):
TS2307: Cannot find module './Interstitials.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Interstitials/FabricIOSPage.tsx(2,31):
TS2307: Cannot find module './Interstitials.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Interstitials/FabricJSPage.tsx(3,31):
TS2307: Cannot find module './Interstitials.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Overviews/ComponentsPage.tsx(4,31):
TS2307: Cannot find module './Overviews.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Overviews/StylesPage.tsx(4,31):
TS2307: Cannot find module './Overviews.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/ResourcesPage/ResourcesPage.tsx(4,31):
TS2307: Cannot find module './ResourcesPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Styles/BrandIconsPage/BrandIconsPage.tsx(7,31):
TS2307: Cannot find module './BrandIconsPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Styles/ColorsPage/ColorsPage.tsx(6,31):
TS2307: Cannot find module './ColorsPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Styles/IconsPage/IconsPage.tsx(6,31):
TS2307: Cannot find module './IconsPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Styles/LayoutPage/LayoutPage.tsx(5,31):
TS2307: Cannot find module './LayoutPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Styles/LocalizationPage/LocalizationPage.tsx(6,31):
TS2307: Cannot find module './LocalizationPage.module.scss'.
ERROR in C:/Users/liuyang/ReactProjects/office-ui-fabric-react/apps/fabric-website/src/pages/Styles/TypographyPage/TypographyPage.tsx(5,31):
TS2307: Cannot find module './TypographyPage.module.scss'.
Version: typescript 2.8.4
Time: 14371ms
i ｢wdm｣: Compiling...
  0% compilingi ｢wdm｣: wait until bundle finished: /fabric-sitev5.js

<--- Last few GCs --->

[7020:000002ED84BCEA60]   135577 ms: Mark-sweep 1360.8 (1456.1) -> 1360.7 (1430.1) MB, 622.7 / 0.5 ms  (average mu = 0.109, current mu = 0.001) last resort GC in old space requested
[7020:000002ED84BCEA60]   136222 ms: Mark-sweep 1360.7 (1430.1) -> 1360.6 (1428.1) MB, 644.7 / 0.4 ms  (average mu = 0.056, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002ECCBADC5C1]
    1: StubFrame [pc: 000002ECCBADD9BF]
Security context: 0x0106b211e6e1 <JSObject>
    2: resolve [000001112C262D09] [path.js:~138] [pc=000002ECCC2571B9](this=0x00f452c022a1 <Object map = 00000125AD736449>)
    3: arguments adaptor frame: 1->0
    4: stat [00000186501048B1] [fs.js:~811] [pc=000002ECCC2482AB](this=0x031a03d0e8d1 <Object map = 0000018ED54CA2F1>,path=0x012999639ae9 <String[232]: C:\Us...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7AC69ECF5
 2: 00007FF7AC6781A6
 3: 00007FF7AC678BB0
 4: 00007FF7AC909AAE
 5: 00007FF7AC9099DF
 6: 00007FF7ACE47724
 7: 00007FF7ACE3DE87
 8: 00007FF7ACE3C3FC
 9: 00007FF7ACE45377
10: 00007FF7ACE453F6
11: 00007FF7AC9E84B7
12: 00007FF7ACA8019A
13: 000002ECCBADC5C1
child_process.js:651
    throw err;
    ^

Error: Command failed: node C:\Users\liuyang\ReactProjects\office-ui-fabric-react\scripts\node_modules\webpack-dev-server\bin\webpack-dev-server.js --config C:\Users\liuyang\ReactProjects\office-ui-fabric-react\apps\fabric-website\webpack.serve.config.js --open
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at myExecSync (C:\Users\liuyang\ReactProjects\office-ui-fabric-react\scripts\exec-sync.js:17:18)
    at Object.<anonymous> (C:\Users\liuyang\ReactProjects\office-ui-fabric-react\scripts\start.js:28:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node ../../scripts/start.js
Directory: C:\\Users\\liuyang\\ReactProjects\\office-ui-fabric-react\\apps\\fabric-website
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\liuyang\\ReactProjects\\office-ui-fabric-react\\apps\\fabric-website\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 
#### Expected behavior:
 
npm run works

**Comment by ecraig12345** [comment]
Hi @liuyangc3, what happens if you try running `npm start` in the root folder (`office-ui-fabric-react` unless you renamed it) instead of in `apps/fabric-website`? That's generally what we recommend to start out. (If you were following some instructions that said to run the command in fabric-website, let me know where you saw that and I'll update it.)

**Comment by liuyangc3** [comment]
> what happens if you try running npm start in the root folder

no erros, thanks

> If you were following some instructions that said to run the command in fabric-website, let me know where you saw that and I'll update it.

yes, I was following https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/fabric-website/README.md#build-the-website

**Comment by liuyangc3** [comment]
I add block to `fabric-website-resources/webpack.serve.config.js`
```
  devServer: {
    port: 8080,
    host: '0.0.0.0'
  },
```
then use a domain  - which dns resove to this  dev server -  
to access  fabric-website-resourcesm Browser return  `Invalid Host header`

**Comment by liuyangc3** [comment]
`fabric-website-resources` now can open, add `disableHostCheck` true fix it.
```json 
devServer: {
   port: 8080,
   host: '0.0.0.0',
  disableHostCheck: true
}
```
`fabric-website` still can not work

**Comment by cliffkoh** [comment]
I'm not sure if fabric-website is intended to be `npm start` (will have to confirm with people who own this). Is there a reason you want to `npm start` in fabric-website?

**Comment by liuyangc3** [comment]
@cliffkoh  yes , I was interesting about it's searchbox with Nav in `Component` page, so I want to start a dev env.

**Comment by cliffkoh** [comment]
Hi @liuyangc3, assuming I understood you correctly, you do not need to NPM start in fabric-website for that. You should do `npm start` in the root folder or `packages/office-ui-fabric-react` folder.

**Comment by liuyangc3** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/fabric-website/README.md#build-the-website @cliffkoh , I got it,  dose this document  needs to be update?

**Comment by liuyangc3** [comment]
npm start in the root folder or packages/office-ui-fabric-react folder.   it starts a project `apps/fabric-website-resources`

but I need to start `apps/fabric-website`, if it can not be build, it should be list in it's document.

**Comment by cliffkoh** [comment]
Hey @liuyangc3, I'm still not understanding what you're trying to do that you need to `npm start` the website. To have a local dev environment, you can do it at `fabric-website-resources` which will have the components and example pages.

**Comment by liuyangc3** [comment]
Acctully I dont need to run `apps/fabric-website-resources`  in a local dev environment.
the reason I am trying to run  `apps/fabric-website`  is that  I was trying to wirte a Nav  with a searchbox ,  
which  like this (address https://developer.microsoft.com/en-us/fabric)
![image](https://user-images.githubusercontent.com/6705844/50477854-37489d80-0a09-11e9-98c1-a69a9a270cfd.png)

then I found this `searchbox nav` is under project  `apps/fabric-website`  , but it's [impl](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/fabric-website/src/components/Nav/Nav.tsx) is not using Nav from `office-ui-fabric-react/lib/Nav`
 
I need to debug this Nav in a dev environment. and trying to rewrite it by using  `office-ui-fabric-react/lib/Nav`

**Comment by ecraig12345** [comment]
Probably `@uifabric/experiments` hasn't been built yet. From the root, try running `npm run buildfast` (or `rush build`) to build all the projects including experiments. Then retry `npm start` in `fabric-website`.

**Comment by liuyangc3** [comment]
@ecraig12345 `npm run buildfast` works, and please update the document in `apps/fabric-website`

**Comment by ecraig12345** [comment]
Thanks for the update! I'm actually going to reopen this for now to track updating the docs.
