### ISSUE TITLE
npm install fails with E404 on @uifabric/set-version

### ISSUE THREAD

**Issue by OutlawAndy** [OfficeDev/office-ui-fabric-react#8481]
running `npm install --save office-ui-fabric-react` fails with the following output

    npm ERR! code E404
    npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uifabric%2fset-version - Not Found
    npm ERR! 404
    npm ERR! 404  '@uifabric/set-version@>=1.1.3 <2.0.0' is not in the npm registry.
    npm ERR! 404 Your package name is not valid, because
    npm ERR! 404  1. name can only contain URL-friendly characters
    npm ERR! 404 It was specified as a dependency of 'office-ui-fabric-react'
    npm ERR! 404
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

Environment:

    macOS 10.13.6
    node v11.12.0
    npm  v6.7.0

Thanks in advance

**Comment by Vitalius1** [comment]
@kenotron @ecraig12345 you would probably have more context here. Thanks!

**Comment by ecraig12345** [comment]
Strange...`@uifabric/set-version@1.1.3` is on the [npm registry](https://www.npmjs.com/package/@uifabric/set-version). Maybe @kenotron or @dzearing will have a better idea of what's going on.

**Comment by OutlawAndy** [comment]
I'm not sure it's `set-version` specifically.  Running the command several more times and it occasionally fails on `@uifabric/foundation@>=0.7.2 <1.0.0` with the same message

**Comment by dzearing** [comment]
@OutlawAndy this could be on your end. Do you have another box to try from?

It could be something in your .npmrc that is redirecting the default registry location.

**Comment by dzearing** [comment]
fwiw no repro here, npm 6.4.1, node 10.15.0. I noticed you're not on node LTS. It's possible that could be it and there's something foul with the edge build. You could try installing LTS.

![image](https://user-images.githubusercontent.com/1110944/55041569-d40bde80-4fea-11e9-8926-99fc62226a92.png)

**Comment by OutlawAndy** [comment]
Thanks.  I do not have access to a different box.  I realize this is likely an issue with my environment. I'm open to suggestions on how I might isolate it.

Using the versions you suggested, I get a slightly different error, same package. Here is the full log output:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/Outlawandy/.nvm/versions/node/v10.15.0/bin/node',
1 verbose cli   '/Users/Outlawandy/.nvm/versions/node/v10.15.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'office-ui-fabric-react' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session 50ab80272d5966bf
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/office-ui-fabric-react 217ms (from cache)
8 silly pacote tag manifest for office-ui-fabric-react@latest fetched in 264ms
9 timing stage:loadCurrentTree Completed in 427ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule office-ui-fabric-react@6.161.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/tslib 129ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/prop-types 130ms (from cache)
19 silly pacote range manifest for tslib@^1.7.1 fetched in 131ms
20 silly resolveWithNewModule tslib@1.9.3 checking installable status
21 silly pacote range manifest for prop-types@^15.5.10 fetched in 132ms
22 silly resolveWithNewModule prop-types@15.7.2 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/@microsoft%2fload-themed-styles 342ms (from cache)
24 silly pacote range manifest for @microsoft/load-themed-styles@^1.7.13 fetched in 345ms
25 silly resolveWithNewModule @microsoft/load-themed-styles@1.8.74 checking installable status
26 http fetch GET 404 https://registry.npmjs.org/@uifabric%2fset-version 476ms
27 silly fetchPackageMetaData error for @uifabric/set-version@>=1.1.3 <2.0.0 404 Not Found: @uifabric/set-version@>=1.1.3 <2.0.0
28 http fetch GET 304 https://registry.npmjs.org/@uifabric%2ficons 508ms (from cache)
29 silly pacote range manifest for @uifabric/icons@>=6.5.0 <7.0.0 fetched in 511ms
30 silly resolveWithNewModule @uifabric/icons@6.5.0 checking installable status
31 http fetch GET 304 https://registry.npmjs.org/@uifabric%2fmerge-styles 535ms (from cache)
32 silly pacote range manifest for @uifabric/merge-styles@>=6.16.1 <7.0.0 fetched in 540ms
33 silly resolveWithNewModule @uifabric/merge-styles@6.16.1 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/@uifabric%2futilities 538ms (from cache)
35 silly pacote range manifest for @uifabric/utilities@>=6.35.1 <7.0.0 fetched in 542ms
36 silly resolveWithNewModule @uifabric/utilities@6.35.1 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/@uifabric%2fstyling 545ms (from cache)
38 silly pacote range manifest for @uifabric/styling@>=6.45.0 <7.0.0 fetched in 550ms
39 silly resolveWithNewModule @uifabric/styling@6.45.0 checking installable status
40 http fetch GET 404 https://registry.npmjs.org/@uifabric%2ffoundation 561ms
41 silly fetchPackageMetaData error for @uifabric/foundation@>=0.7.2 <1.0.0 404 Not Found: @uifabric/foundation@>=0.7.2 <1.0.0
42 timing stage:rollbackFailedOptional Completed in 1ms
43 timing stage:runTopLevelLifecycles Completed in 1008ms
44 silly saveTree test
44 silly saveTree └─┬ office-ui-fabric-react@6.161.0
44 silly saveTree   ├── @microsoft/load-themed-styles@1.8.74
44 silly saveTree   ├─┬ @uifabric/icons@6.5.0
44 silly saveTree   │ ├─┬ @uifabric/styling@6.45.0
44 silly saveTree   │ │ ├─┬ @uifabric/merge-styles@6.16.1
44 silly saveTree   │ │ │ └── tslib@1.9.3
44 silly saveTree   │ │ ├─┬ @uifabric/utilities@6.35.1
44 silly saveTree   │ │ │ └── prop-types@15.7.2
44 silly saveTree   │ │ └── tslib@1.9.3
44 silly saveTree   │ └── tslib@1.9.3
44 silly saveTree   ├── @uifabric/merge-styles@6.16.1
44 silly saveTree   ├── @uifabric/styling@6.45.0
44 silly saveTree   ├── @uifabric/utilities@6.35.1
44 silly saveTree   ├── prop-types@15.7.2
44 silly saveTree   └── tslib@1.9.3
45 verbose stack Error: 404 Not Found: @uifabric/set-version@>=1.1.3 <2.0.0
45 verbose stack     at fetch.then.res (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
45 verbose stack     at tryCatcher (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
45 verbose stack     at Promise._settlePromiseFromHandler (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
45 verbose stack     at Promise._settlePromise (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
45 verbose stack     at Promise._settlePromise0 (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
45 verbose stack     at Promise._settlePromises (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
45 verbose stack     at Async._drainQueue (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
45 verbose stack     at Async._drainQueues (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
45 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/Outlawandy/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
45 verbose stack     at runCallback (timers.js:705:18)
45 verbose stack     at tryOnImmediate (timers.js:676:5)
45 verbose stack     at processImmediate (timers.js:658:5)
46 verbose cwd /Users/Outlawandy/CODE/ngdc/word/test
47 verbose Darwin 17.7.0
48 verbose argv "/Users/Outlawandy/.nvm/versions/node/v10.15.0/bin/node" "/Users/Outlawandy/.nvm/versions/node/v10.15.0/bin/npm" "install" "--save" "office-ui-fabric-react"
49 verbose node v10.15.0
50 verbose npm  v6.4.1
51 error code E404
52 error 404 Not Found: @uifabric/set-version@>=1.1.3 <2.0.0
53 verbose exit [ 1, true ]
```

**Comment by dzearing** [comment]
Clear NPM cache:

```bash
npm cache clean
```

Any difference?

**Comment by OutlawAndy** [comment]
no difference..

However, I was able to download the tarball directly for the 2 packages that were giving me problems (set-version & foundation) and then `npm i /local/path/to.tgz`

with those 2 already in `./node_modules`, `npm install --save office-ui-fabric-react` finally succeeded. 🍻

Thanks for your help.
